# Generated by Django 5.0.3 on 2024-03-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TL', 'Tele'), ('RD', 'Radio'), ('SH', 'shoes'), ('WT', 'Watch'), ('PH', 'Phone'), ('LT', 'Laptop'), ('FT', 'Fruit')], max_length=2),
        ),
    ]
