# Generated by Django 5.0.3 on 2024-03-10 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PH', 'Phone'), ('TL', 'Tele'), ('LT', 'Laptop'), ('RD', 'Radio'), ('WT', 'Watch'), ('FT', 'Fruit'), ('SH', 'shoes')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Jigawa', 'Jigawa'), ('Kwara', 'Kwara'), ('Enugu', 'Enugu'), ('Yobe', 'Yobe'), ('Adamawa', 'Adamawa'), ('Katsina', 'Katsina'), ('Bayelsa', 'Bayelsa'), ('Kano', 'Kano'), ('Kebbi', 'Kebbi'), ('Zamfara', 'Zamfara'), ('Kogi', 'Kogi'), ('Gombe', 'Gombe'), ('Edo', 'Edo'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Sokoto', 'Sokoto'), ('Kaduna', 'Kaduna'), ('Ondo', 'Ondo'), ('Benue', 'Benue'), ('Oyo', 'Oyo'), ('Ekiti', 'Ekiti'), ('FCT', 'FCT'), ('Taraba', 'Taraba'), ('Abia', 'Abia'), ('Imo', 'Imo'), ('Ogun', 'Ogun'), ('Ebonyi', 'Ebonyi'), ('Rivers', 'Rivers'), ('Bauchi', 'Bauchi'), ('Borno', 'Borno'), ('Nasarawa', 'Nasarawa'), ('Delta', 'Delta'), ('Cross River', 'Cross River'), ('Osun', 'Osun'), ('Lagos', 'Lagos'), ('Plateau', 'Plateau'), ('Niger', 'Niger')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
