# Generated by Django 5.0.3 on 2024-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('FCT', 'FCT'), ('Ebonyi', 'Ebonyi'), ('Zamfara', 'Zamfara'), ('Bayelsa', 'Bayelsa'), ('Borno', 'Borno'), ('Gombe', 'Gombe'), ('Sokoto', 'Sokoto'), ('Oyo', 'Oyo'), ('Edo', 'Edo'), ('Anambra', 'Anambra'), ('Enugu', 'Enugu'), ('Taraba', 'Taraba'), ('Bauchi', 'Bauchi'), ('Benue', 'Benue'), ('Lagos', 'Lagos'), ('Adamawa', 'Adamawa'), ('Cross River', 'Cross River'), ('Kogi', 'Kogi'), ('Rivers', 'Rivers'), ('Imo', 'Imo'), ('Katsina', 'Katsina'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Kwara', 'Kwara'), ('Jigawa', 'Jigawa'), ('Kebbi', 'Kebbi'), ('Akwa Ibom', 'Akwa Ibom'), ('Yobe', 'Yobe'), ('Ekiti', 'Ekiti'), ('Niger', 'Niger'), ('Ondo', 'Ondo'), ('Plateau', 'Plateau'), ('Ogun', 'Ogun'), ('Osun', 'Osun'), ('Nasarawa', 'Nasarawa'), ('Abia', 'Abia'), ('Delta', 'Delta')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'shoes'), ('FT', 'Fruit'), ('LT', 'Laptop'), ('PH', 'Phone'), ('RD', 'Radio'), ('TL', 'Tele'), ('WT', 'Watch')], max_length=2),
        ),
    ]
