# Generated by Django 5.0.3 on 2024-03-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_customer_state_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bayelsa', 'Bayelsa'), ('Kwara', 'Kwara'), ('Enugu', 'Enugu'), ('Cross River', 'Cross River'), ('Sokoto', 'Sokoto'), ('Plateau', 'Plateau'), ('Zamfara', 'Zamfara'), ('Benue', 'Benue'), ('Abia', 'Abia'), ('Ogun', 'Ogun'), ('Katsina', 'Katsina'), ('Imo', 'Imo'), ('Gombe', 'Gombe'), ('Borno', 'Borno'), ('Delta', 'Delta'), ('Kaduna', 'Kaduna'), ('Edo', 'Edo'), ('Kano', 'Kano'), ('Osun', 'Osun'), ('Ondo', 'Ondo'), ('Lagos', 'Lagos'), ('Anambra', 'Anambra'), ('Nasarawa', 'Nasarawa'), ('Akwa Ibom', 'Akwa Ibom'), ('FCT', 'FCT'), ('Bauchi', 'Bauchi'), ('Ekiti', 'Ekiti'), ('Ebonyi', 'Ebonyi'), ('Rivers', 'Rivers'), ('Adamawa', 'Adamawa'), ('Kebbi', 'Kebbi'), ('Taraba', 'Taraba'), ('Oyo', 'Oyo'), ('Jigawa', 'Jigawa'), ('Yobe', 'Yobe'), ('Kogi', 'Kogi'), ('Niger', 'Niger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PH', 'Phone'), ('TL', 'Tele'), ('FT', 'Fruit'), ('SH', 'shoes'), ('LT', 'Laptop'), ('RD', 'Radio'), ('WT', 'Watch')], max_length=2),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
