# Generated by Django 5.0.3 on 2024-03-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_customer_state_alter_product_category_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Katsina', 'Katsina'), ('Ogun', 'Ogun'), ('Yobe', 'Yobe'), ('Taraba', 'Taraba'), ('Ebonyi', 'Ebonyi'), ('Osun', 'Osun'), ('Kebbi', 'Kebbi'), ('Cross River', 'Cross River'), ('Kogi', 'Kogi'), ('Bayelsa', 'Bayelsa'), ('Lagos', 'Lagos'), ('Adamawa', 'Adamawa'), ('Anambra', 'Anambra'), ('Kwara', 'Kwara'), ('Imo', 'Imo'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Kano', 'Kano'), ('Gombe', 'Gombe'), ('Kaduna', 'Kaduna'), ('Edo', 'Edo'), ('Borno', 'Borno'), ('Nasarawa', 'Nasarawa'), ('Ondo', 'Ondo'), ('Niger', 'Niger'), ('Zamfara', 'Zamfara'), ('Oyo', 'Oyo'), ('Abia', 'Abia'), ('Enugu', 'Enugu'), ('Benue', 'Benue'), ('Ekiti', 'Ekiti'), ('Bauchi', 'Bauchi'), ('Plateau', 'Plateau'), ('Akwa Ibom', 'Akwa Ibom'), ('Jigawa', 'Jigawa'), ('Delta', 'Delta'), ('FCT', 'FCT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'shoes'), ('PH', 'Phone'), ('TL', 'Tele'), ('FT', 'Fruit'), ('WT', 'Watch'), ('RD', 'Radio'), ('LT', 'Laptop')], max_length=2),
        ),
    ]
