# Generated by Django 4.2.5 on 2024-03-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Enugu', 'Enugu'), ('Cross River', 'Cross River'), ('Sokoto', 'Sokoto'), ('Ebonyi', 'Ebonyi'), ('Kwara', 'Kwara'), ('Bauchi', 'Bauchi'), ('Kano', 'Kano'), ('Delta', 'Delta'), ('Imo', 'Imo'), ('Anambra', 'Anambra'), ('FCT', 'FCT'), ('Rivers', 'Rivers'), ('Plateau', 'Plateau'), ('Nasarawa', 'Nasarawa'), ('Ondo', 'Ondo'), ('Jigawa', 'Jigawa'), ('Lagos', 'Lagos'), ('Oyo', 'Oyo'), ('Borno', 'Borno'), ('Edo', 'Edo'), ('Niger', 'Niger'), ('Yobe', 'Yobe'), ('Ekiti', 'Ekiti'), ('Osun', 'Osun'), ('Bayelsa', 'Bayelsa'), ('Akwa Ibom', 'Akwa Ibom'), ('Katsina', 'Katsina'), ('Adamawa', 'Adamawa'), ('Gombe', 'Gombe'), ('Taraba', 'Taraba'), ('Ogun', 'Ogun'), ('Kaduna', 'Kaduna'), ('Kebbi', 'Kebbi'), ('Zamfara', 'Zamfara'), ('Kogi', 'Kogi'), ('Benue', 'Benue'), ('Abia', 'Abia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PH', 'Phone'), ('RD', 'Radio'), ('WT', 'Watch'), ('FT', 'Fruit'), ('LT', 'Laptop'), ('TL', 'Tele'), ('SH', 'shoes')], max_length=2),
        ),
    ]
